 // WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
 
 const awsmobile = {
     "aws_project_region": "us-west-2",
     "aws_cognito_identity_pool_id": "us-west-2:0cc33185-96f7-46fc-ba2f-06d6231759bd",
     "aws_cognito_region": "us-west-2",
     "aws_user_pools_id": "us-west-2_TRS9qRkBt",
     "aws_user_pools_web_client_id": "1ulqglllu89u6hevr2vn4bk2c3",
     "oauth": {}
 };
 
 
 export default awsmobile;
 