// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:29ff6521-3975-40df-b5f1-c929a78d0447",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_O5k1nBPfT",
    "aws_user_pools_web_client_id": "777sfibg218veg9m6cfvjsjvan",
    "aws_content_delivery_bucket": "dz-react-ui-20191004073718-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://dd1v498osgsh3.cloudfront.net"
};


export default awsmobile;
